### ISSUE TITLE
Is it a proper choice if we remain a requirement of EF Core 2.x ?

### ISSUE THREAD

**Issue by arthuridea** [casbin-net/EFCore-Adapter#20]
I noticed that the nuget package forced requires EF Core >=3.1.3 from v1.2.0. 
![image](https://user-images.githubusercontent.com/2337583/84608592-bd022680-aee5-11ea-9b70-2ff0f09ca088.png)
I briefly checked the latest code and there's no conflict with EF Core 2.x.
As Casbin.NET package still support netstandard2.0(netcore 2.x),how about remain EF Core 2.x requirement until Casbin.NET package update? There is some [breaking changes in ef core 3.x](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes).some of old project is still based on netCore2.x LTS and ef core 2.x

**Comment by hsluoyz** [comment]
@huazhikui @xcaptain @nodece @Sagilio why and when did we increase the version bar? Can we resolve this issue?

**Comment by huazhikui** [comment]
I think we should use ef core 2.x, which can support .net Core2.x LTS, do you think ？@xcaptain

**Comment by xcaptain** [comment]
Sorry I didn't review well, the `sqlserver` dependency was introduces at https://github.com/casbin-net/EFCore-Adapter/commit/2e57b0a501075e74de983f3909d1d0f64926cc98 this commit shouldn't be merged.

The efcore version was updated to 3.1 because my projects have updated to .net core 3, Casbin.NET works well on .net core 3 projects. 

@arthuridea you still want to support .net core 2.2?

**Comment by hsluoyz** [comment]
As a common sense for a library, we should always stay at the lowest compatible version to achieve the widest audience.

In my sense, starting from this PR: https://github.com/casbin-net/EFCore-Adapter/pull/13, all following commits need to be reviewed again and maybe reverted.

![image](https://user-images.githubusercontent.com/3787410/84611984-da3cf200-aef1-11ea-93e6-0e9b6fecdefe.png)

**Comment by hsluoyz** [comment]
@arthuridea can you make a PR to fix it?

If not, @Sagilio can you fix this issue?

**Comment by xcaptain** [comment]
I'm using a fork of efcore-adapter in my project.
![图片](https://user-images.githubusercontent.com/4054836/84612388-16248700-aef3-11ea-91e5-77a7841a5ddf.png)
So these breaking changes didn't affect my project :fearful: 

It's ok for me to support .net core 2.2 at master, but since .net core 2.2 was enf of life https://dotnet.microsoft.com/download/dotnet-core maybe we should better maintain 2 versions at the same time.

**Comment by Sagilio** [comment]
Both `EF core 2.x` and `3.x` are netstandard packages and It looks like the `Microsoft.EntityFrameworkCore` have not an API break change.
I think we need not change any code and only change the dependency to 2.x.
It can be updated by the user with install the new version `Microsoft.EntityFrameworkCore` package.

**Comment by arthuridea** [comment]
> @arthuridea can you make a PR to fix it?
> 
> If not, @Sagilio can you fix this issue?

targetframework is 2.0 then 
`<PackageReference` Include="Microsoft.EntityFrameworkCore" Version="3.1.4" />`
change package version to 2.x will be ok.

**Comment by hsluoyz** [comment]
@huazhikui can you help make a new release?
